### ISSUE TITLE
Severe weather mode exiting

### ISSUE THREAD

**Issue by AnimeFanatic459** [buffbears/Weatherscan#15]
after the simulator runs severe weather mode for a while it refuses to exit it and requires refreshing it to exit it and go back into normal mode. the simulator also doesn't show the weather bulletin during severe weather mode.

**Comment by buffbears** [comment]
Weather bulletin not showing up will be fixed in a new update that includes the severe weather message. If a weather warning is shown on the marquee it does not show on the bulletin. The severe weather message is supposed to show but its not implemented yet. As for the other issues with severe weather mode, I'll review it when I implement severe weather messages.

**Comment by rweldon0828** [comment]
@buffbears When is the next update looking to be? And what are we expecting to change in the new update possibly? Also, I was in Bethany Beach, Delaware last week and saw a real version (not emulated) running on a TV in a convenience store.

**Comment by buffbears** [comment]
Newest update is out and weather bulletin is included, however I can not confirm the sim exits severe weather mode correctly.

**Comment by rweldon0828** [comment]
Another issue with the Severe Weather mode... It's showing this ra
![Capture1](https://user-images.githubusercontent.com/69129972/183319178-dc0eac45-4300-4ac0-b94c-5b08834cf3eb.PNG)
ndom screen while transitioning.

**Comment by AnimeFanatic459** [comment]
Fixed since mine exited severe weather mode fine earlier.
